# action.yml
name: 'Zulip Archive'
description: 'Publish Zulip archive in GitHub pages'
inputs:
  zulip_organization_url:
    description: 'URL of Zulip organization'
    required: true
  zulip_bot_email:
    description: 'Email of the Zulip bot'
    required: true
  zulip_bot_key:
    description: 'API key of the Zulip bot'
    required: true
  github_personal_access_token:
    description: 'GitHub personal access token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.zulip_organization_url }}
    - ${{ inputs.zulip_bot_email }}
    - ${{ inputs.zulip_bot_key }}
    - ${{ inputs.github_personal_access_token }}
